#!/bin/bash
if [ $(id -u) -eq 0 ]; then
        read -p "Enter username : " username
        read -s -p "Enter password : " password
        egrep "^$username" /etc/passwd >/dev/null
        if [ $? -eq 0 ]; then
                echo "$username exists!"
                exit 1
        else
                pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
                useradd -m -p "$pass" "$username"
                [ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
        fi
else
        echo "Only root may add a user to the system."
        exit 2
fi


===================================================================================================

#!/bin/bash
# This scripts is to create users and group

#create group and verify
groupadd  opsadmin && cat /etc/group |grep opsadmin

#create user and password
useradd attacker && echo "Password" | passwd --stdin attacker

#Force the user to reset his/her password
chage -d 0 attacker

#make sure the user reset their login on first attempt
chage -M 60 attacker


echo "I'm done!!!"


